### PR TITLE
Calculate local time offsets correctly

### PR DESCRIPTION
**Pull request by nickpiggott**
Amendments to calculate LTO correctly

### CODE REVIEW

**Comment by nickpiggott** [comment]
Have also fixed a problem with CData strings longer than 252 characters

**Comment by nickpiggott** [comment]
Have added a ton of validation in today to stop the process of parsing the XML in to objects from crashing out and halting midway through an SI file.

**Review by magicbadger — APPROVED** [review]
Thanks!

**Comment by nickpiggott** [comment]
Some changes today to correctly calculate the length of UTF-8 encoded sttings.

**Comment by magicbadger** [comment]
Its a bit complex merging this, not least as I've messed around myself. The validation points on the XML are interesting as the elements missing are required, so they must be present. Likely we need to fail at an earlier stage or find a better workaround.

**Pull request merged**
